import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "PerfectTales terms of service. Read about the terms and conditions for using the PerfectTales bedtime story app.",
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="pt-28 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-extrabold text-foreground mb-8">
            Terms of Service
          </h1>

          <div className="prose prose-lg max-w-none text-muted space-y-6">
            <p>
              Welcome to PerfectTales. By downloading and using our app, you
              agree to these terms of service.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-4">
              Use of Service
            </h2>
            <p>
              PerfectTales provides AI-generated personalized bedtime stories for
              children. The app is intended for use by parents, guardians, and
              caregivers to create stories for children aged 3-11.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-4">
              Content
            </h2>
            <p>
              Stories generated by PerfectTales are created using artificial
              intelligence and are designed to be age-appropriate (rated 4+).
              While we strive to ensure all content is suitable for children, AI
              generation may occasionally produce unexpected results. We
              encourage parents to read stories with their children.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-4">
              In-App Purchases
            </h2>
            <p>
              PerfectTales offers optional in-app purchases through the Apple App
              Store:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Premium Weekly: $3.99/week (auto-renewable)</li>
              <li>Premium Monthly: $17.99/month (auto-renewable)</li>
              <li>Story Pack: $5.99 (one-time purchase)</li>
            </ul>
            <p>
              Subscriptions automatically renew unless cancelled at least 24
              hours before the end of the current period. You can manage and
              cancel subscriptions in your Apple ID account settings.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-4">
              Intellectual Property
            </h2>
            <p>
              Stories generated for your personal use are yours to keep and
              enjoy. The PerfectTales app, brand, and underlying technology
              remain the property of the developer.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-4">
              Limitations
            </h2>
            <p>
              PerfectTales is provided &quot;as is&quot; without warranties of any kind.
              We do not guarantee uninterrupted or error-free service. Story
              generation requires an internet connection; saved stories can be
              read offline.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-4">
              Changes
            </h2>
            <p>
              We may update these terms from time to time. Continued use of the
              app after changes constitutes acceptance of the updated terms.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-10 mb-4">
              Contact
            </h2>
            <p>
              For questions about these terms, please contact us through the App
              Store listing.
            </p>

            <p className="text-sm text-muted/60 mt-10">
              Last updated: February 2025
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
